#                _        _____ _      _
#     /\        | |      |  __ (_)    | |
#    /  \  _   _| |_ ___ | |__) |  ___| | ___   _ _ __
#   / /\ \| | | | __/ _ \|  ___/ |/ __| |/ / | | | '_ \
#  / ____ \ |_| | || (_) | |   | | (__|   <| |_| | |_) |
# /_/    \_\__,_|\__\___/|_|   |_|\___|_|\_\\__,_| .__/
#                                                | |
#                                                |_|
# Config File
# Version: 1.0.4

# Mode can be either "whitelist" or "blacklist"
# whitelist ensures that AutoPickup is only active in the worlds entered below
# blacklist ensures that AutoPickup is deactivated in the worlds entered below
mode: blacklist
# Set whitelist/blacklist worlds here
worlds:
  - placeholder

# Set a pop-up message here that appears when the player's inventory is full.
# Leave blank to disable pop-up messages
full-inventory: '&cYour inventory is full!'
